### ISSUE TITLE
Something is not working

### ISSUE THREAD

**Issue by jano-on-github** [rpeshkov/skype-wrapper#4]
Hey, i just discovered your patched sni-qt package. I use it on Elementary Freya Beta 2 (14.04) and it seems it is not working properly anymore? Is something broken, or is it me? I downloaded your icons and installed them using the script. I also downloaded icons for MEGAsync from elementaryplus. The sni-qt packages have been updated after I added the ppa but still the old icons are used for Skype and MEGAsync.

Any sugestions? Thank you!

**Comment by bil-elmoussaoui** [comment]
I can confirm this; its not working on elementary ferya beta 2

**Comment by rpeshkov** [comment]
Currently I don't have machine with Elementary Freya. I'll try to check this issue as soon as possible.

**Comment by rpeshkov** [comment]
@jano-on-github @bil-elmoussaoui just checked patched Sni-Qt on Elementary Freya Beta 2. Everything works fine.
Can you tell me how you install patched Sni-Qt? Have you upgraded system after adding PPA?

**Comment by jano-on-github** [comment]
Hey! Thanks for your super fast response. I added the PPA, updatet and upgraded (used dist-upgrade to be sure). Then I used the script to copy the icons to the correct folder. Everything seems to be just fine, except that the old icons show up.

![desktop](https://cloud.githubusercontent.com/assets/7703423/6492724/def2c3f2-c2b5-11e4-9ed1-e32c243c76e4.png)

**Comment by jano-on-github** [comment]
Okay, just solved the issue. I put the icons in my home folder but I need to but them in the /usr/share/. Then it's working! Sorry!
