### ISSUE TITLE
Blurred icons in Elementary OS Freya

### ISSUE THREAD

**Issue by matasarei** [rpeshkov/skype-wrapper#5]
Hello! Can you fix that (and maybe make it a bit smaller)? Thank you!
![skype](https://cloud.githubusercontent.com/assets/6638367/8024585/0b3e2930-0d41-11e5-992f-a4fcda2c1052.jpg)

**Comment by bil-elmoussaoui** [comment]
@matasarei try using this https://github.com/mank319/elementaryPlus

**Comment by matasarei** [comment]
@bil-elmoussaoui Yes, it works! Thank you!
